# 마이크로태스크



> 출처 - [**모던 JS 튜토리얼**](https://ko.javascript.info/)을 보고 정리한 글입니다.



<br>



- 프라미스 핸들러 `.then/catch/finally`는 항상 비동기적으로 실행된다.
- 프라미스가 즉시 이행되더라도 `.then/catch/finally` 아래에 있는 코드는 이 핸들러들이 실행되기 전에 실행된다.

### 예시

```javascript
let promise = Promise.resolve();

promise.then(()) => alert('프라미스 성공');

alert('코드 종료'); // 이 얼럿창이 가장 먼저 뜬다.
```

<br>

## 1. 마이크로태스크 큐

- 비동기 작업을 처리하기위한 적절한 관리를 위해 ECMA에선 `PromiseJobs`라는 내부 큐(internal queue)를 명시한다.
- V8 엔진에서는 이를 **마이크로태스크 큐(microtask queue)**라고 부른다.

<br>

> **마이크로태스크 큐**
>
> - 마이크로태스크 큐는 먼저 들어온 작업을 먼저 실행한다. (FIFO, First-In-First-Out)
> - 실행할 것이 아무것도 남아있지 않을 때만 마이크로태스크 큐에 있는 작업이 실행된다.

<br>

즉, 어떤 프라미스가 준비되었을 때 이 프라미스의 `.then/catch/finally` 핸들러가 큐에 들어간다.

이때 핸들러는 실행되지 않고, 현재 코드에서 실행할 것이 아무것도 없을 때 자바스크립트 엔진은 큐에서 작업을 꺼내 실행한다.

<br>

예시에서는 **'코드종료'** ▶️ **'프라미스 성공'** 의 순서로 얼럿창이 떴다.

**'프라미스 성공'** ▶️ **'코드종료'** 처럼 실행 순서를 바꾸고 싶을 경우에는 `.then`을 사용해 큐에 넣어주면 된다.

```javascript
Proime.resolve()
	.then(() => alert('프라미스 성공'))
	.then(() => alert('코드 종료'));
```

<br>

## 2. 처리되지 못한 거부

- 처리되지 못한 거부는 **마이크로태스크 큐 끝에서 프라미스 에러가 처리되지 못할 때 발생**한다.

- 정상적인 경우라면 에러가 생길 것을 대비하여 프라미스 체인에 `.catch`를 추가해 에러를 처리한다.
- 하지만 `.catch`가 없는 경우, 엔진은 마이크로태스크 큐가 빈 이후에 `unhandledrejection` 이벤트를 트리거한다.

### 예시

```javascript
let promise = Promise.reject(new Error('프라미스 실패!!'));

// 프라미스 실패!!
window.addEventListener('unhandledrejection', event => alert(event.reason));
```

<br>

### setTimeout으로 에러를 나중에 처리하기

```javascript
let promise = Promise.reject(new Error('프라미스 실패!!'));
setTimeout(() => promise.catch(err => alert('에러를 잡았다!')), 1000);

window.addEventListener('unhandledrejection', event => alert(event.reason));

// Error: 프라미스 실패!! -> 에러를 잡았다!
```

- `unhandledrejection`은 마이크로태스크 큐에 있는 작업 모두가 완료되었을 때 생성된다.
- 엔진은 프라미스들을 검사하고 이 중 하나라도 거부(rejected) 상태이면 `unhandledrejection` 핸들러를 트리거한다.
- 위 예시는 `setTimeout`을 사용해 추가한 `.catch` 역시 트리거 되지만, `.catch`는 `unhandledrejection`이 발생한 이후에 트리거 되므로 `프라미스 실패!!`가 출력된다.